name: CD - AWS BEANSTALK
on:
    workflow_dispatch:
env:
  SLN_NAME: aws_demos_netframework.sln
  SLN_OUTPUT_PATH: ../../_build
  BUILD_FOLDER_PATH_AND_NAME: './_build'
  ARTIFACT_NAME: 'deployment-package'

  ENV_STG_URL: 'http://mvc-demo-netframework-env-staging.eba-vu2rymzm.us-east-2.elasticbeanstalk.com'
  ENV_QA_URL: 'http://mvc-demo-netframework-env-qa.eba-vu2rymzm.us-east-2.elasticbeanstalk.com'
jobs:
    Info:
        runs-on: windows-2022
        steps:
            - name: check github.event_name
              run: echo "${{ github.event_name }}"

            - name: check github.event.ref
              run: echo "${{ github.event.ref }}"

    Build:
        needs: Info
        runs-on: windows-2022
        steps:
            - uses: actions/checkout@v4

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2

            - name: Setup NuGet
              uses: nuget/setup-nuget@v2

            - name: Navigate to Workspace
              run: cd $GITHUB_WORKSPACE

            - name: Create Build Directory
              run: mkdir ${{ env.BUILD_FOLDER_PATH_AND_NAME }}

            - name: Restore Packages
              run: nuget restore ${{ env.SLN_NAME }}

            - name: Build solution
              run: |
                msbuild ${{ env.SLN_NAME }} /t:Build /p:Configuration=Release /p:OutputPath=${{ env.SLN_OUTPUT_PATH }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.ARTIFACT_NAME }}
                path: "${{ env.BUILD_FOLDER_PATH_AND_NAME }}"

    DeployStaging:
        name: Deploy to Staging
        if: github.event_name == 'workflow_dispatch' && github.event.ref == 'refs/heads/main'
        needs: Build
        runs-on: windows-2022
        environment:
            name: STAGING
            url: ${{ env.ENV_STG_URL }}
        steps:
            - name: Deploy
              run: echo I am deploying to staging!

    DeployQA:
        name: Deploy to QA
        needs: DeployStaging
        runs-on: windows-2022
        environment:
            name: QA
            url: ${{ env.ENV_QA_URL }}
        steps:
            - name: Deploy
              run: echo I am deploying to qa!
